version: '3'
services:
  mariadb:
    image: imageConfig
    volumes:
      - volumesConfig
    ports:
      - 'portConfig:portConfig'
    environment:
      nameVarPassword: passwordConfig
      nameVarDatabase: databaseConfig
