version: '3'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - /tmp/dc-test-db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bd_deelop_test
